
services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@mysql/project_db

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project_db
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
